name: automerge_v2
on:
  workflow_run:
    workflows:
      - "Criar PR em homologação"
    branches:
      - main
    types:
      - completed

jobs:
  update-cms-master:
    name: Merge main into homologacao after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'main'
          target: 'homologacao'