name: Criar PR em homologação
on:
  push:
    branches:
      - main
jobs:
  syncMainHomo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout for PR
        uses: actions/checkout@v3
        with:
          ref: homologacao
      - name: Reseta branch de homologacao
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Cria o PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: main
      - name: checkout for Merge
        uses: actions/checkout@v3
      - name: Merging
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'main'
          target: 'homologacao'
