name: Criar PR em homologação
on:
  push:
    branches:
      - main #Repositório que irá receber o push e ativar o fluxo
jobs:
  syncMainHomo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout for PR
        uses: actions/checkout@v3
        with:
          ref: homologacao #Repositório que irá receber o PR
      - name: Reseta branch de homologacao #necessário alterar os paths do fetch abaixo para funcionar no repo da sensedia
        run: |
          git fetch origin main:main 
          git reset --hard main
      - name: Cria o PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: main #Aqui a gente define a partir de qual branch será feito PR
      # Não sei se é necessário este ultimo checkout mas como tava no script que eu usei de cola, resolvi deixar.
      - name: checkout for Merge
        uses: actions/checkout@v3
      - name: Merging
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'main' #nome da branch onde estão as alterações
          target: 'homologacao' #nome da branch que irá receber as alterações
          